import { useCallback, useEffect, useState } from 'react'
import { KeyRound, ShieldCheck, Trash2 } from 'lucide-react'
import { supabase } from '../../lib/supabase'

type Factor = { id: string; friendly_name?: string; status: 'verified' | 'unverified'; factor_type: string; created_at: string }
type Enrollment = { id: string; qrCode: string; secret: string }

export function AdminMfa({ required = false, onVerified }: { required?: boolean; onVerified?: () => void }) {
  const [factors, setFactors] = useState<Factor[]>([]); const [enrollment, setEnrollment] = useState<Enrollment | null>(null); const [code, setCode] = useState(''); const [busy, setBusy] = useState(true); const [error, setError] = useState(''); const [success, setSuccess] = useState('')
  const load = useCallback(async () => { setBusy(true); setError(''); const { data, error: listError } = await supabase.auth.mfa.listFactors(); if (listError) setError(listError.message); else setFactors((data.totp || []) as Factor[]); setBusy(false) }, [])
  useEffect(() => { let active = true; void supabase.auth.mfa.listFactors().then(({ data, error: listError }) => { if (!active) return; if (listError) setError(listError.message); else setFactors((data.totp || []) as Factor[]); setBusy(false) }); return () => { active = false } }, [])
  async function enroll() { setBusy(true); setError(''); setSuccess(''); const { data, error: enrollError } = await supabase.auth.mfa.enroll({ factorType: 'totp', friendlyName: 'Karla Premium Admin' }); if (enrollError) setError(enrollError.message); else setEnrollment({ id: data.id, qrCode: data.totp.qr_code, secret: data.totp.secret }); setBusy(false) }
  async function verify(factorId: string) { if (!/^\d{6}$/.test(code)) { setError('Digite o código de 6 dígitos do aplicativo autenticador.'); return } setBusy(true); setError(''); const { data: challenge, error: challengeError } = await supabase.auth.mfa.challenge({ factorId }); if (challengeError) { setError(challengeError.message); setBusy(false); return } const { error: verifyError } = await supabase.auth.mfa.verify({ factorId, challengeId: challenge.id, code }); if (verifyError) setError('Código inválido ou expirado. Tente novamente.'); else { setCode(''); setEnrollment(null); setSuccess('Autenticação multifator confirmada.'); await load(); onVerified?.() } setBusy(false) }
  async function remove(factor: Factor) { if (!window.confirm(`Remover o fator “${factor.friendly_name || 'Aplicativo autenticador'}”?`)) return; setBusy(true); setError(''); const { error: removeError } = await supabase.auth.mfa.unenroll({ factorId: factor.id }); if (removeError) setError(removeError.message); else { setSuccess('Fator removido com sucesso.'); await load() } setBusy(false) }
  const verified = factors.filter((factor) => factor.status === 'verified')
  const challengeFactor = enrollment ? { id: enrollment.id } : verified[0]
  return <section className={`mfa-panel${required ? ' mfa-panel--gate' : ''}`} aria-labelledby="mfa-title"><div className="mfa-icon"><ShieldCheck aria-hidden="true" /></div><div><span className="admin-eyebrow">Segurança da conta</span><h1 id="mfa-title">{required ? 'Confirme sua identidade' : 'Autenticação multifator'}</h1><p>{required ? 'A área administrativa exige uma segunda etapa de autenticação.' : 'Proteja o acesso administrativo com um aplicativo autenticador.'}</p></div>
    {busy && !factors.length && <div className="admin-skeleton" aria-label="Carregando fatores"><i /><i /></div>}
    {error && <p className="admin-alert error" role="alert">{error}</p>}{success && <p className="admin-alert success" role="status">{success}</p>}
    {!busy && !challengeFactor && !enrollment && <button className="admin-primary" onClick={() => void enroll()}><KeyRound />Ativar aplicativo autenticador</button>}
    {enrollment && <div className="mfa-enrollment"><p>Leia o QR Code no Google Authenticator, Microsoft Authenticator, 1Password ou aplicativo compatível.</p><img src={enrollment.qrCode} alt="QR Code para configurar autenticação multifator" /><details><summary>Não consegue ler o QR Code?</summary><code>{enrollment.secret}</code></details></div>}
    {challengeFactor && <form className="mfa-challenge" onSubmit={(event) => { event.preventDefault(); void verify(challengeFactor.id) }}><label>Código de verificação<input inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} value={code} onChange={(e) => setCode(e.target.value.replace(/\D/g, ''))} placeholder="000000" required /></label><button className="admin-primary" disabled={busy}>{busy ? 'Verificando…' : enrollment ? 'Confirmar ativação' : 'Verificar e continuar'}</button></form>}
    {!required && verified.length > 0 && <div className="mfa-factors"><h2>Fatores ativos</h2>{verified.map((factor) => <article key={factor.id}><div><ShieldCheck /><span><strong>{factor.friendly_name || 'Aplicativo autenticador'}</strong><small>Ativo desde {new Intl.DateTimeFormat('pt-BR').format(new Date(factor.created_at))}</small></span></div><button onClick={() => void remove(factor)} disabled={busy} aria-label="Remover fator"><Trash2 /></button></article>)}<button className="admin-secondary" onClick={() => void enroll()} disabled={busy}>Adicionar outro autenticador</button></div>}
  </section>
}